name: Build APK from direct URL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download project ZIP
        run: |
          set -e
          DIRECT_URL="https://farhadsan.ir/an1.zip"  # ← لینک مستقیم هاست خودت
          curl -L --fail -o src.zip "$DIRECT_URL"
          ls -lh src.zip

      - name: Unzip project
        run: |
          mkdir -p src
          unzip -q src.zip -d src
          echo "Top level:"
          ls -la src | head -n 200

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK platforms & build-tools
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "platforms;android-33"

      - name: Locate Gradle wrapper
        id: findgradle
        run: |
          set -e
          WRAP=$(find src -name gradlew -type f | head -n1)
          if [ -z "$WRAP" ]; then
            echo "No gradlew found!" >&2
            exit 1
          fi
          echo "wrap=$WRAP" >> $GITHUB_OUTPUT
          echo "Found gradlew at: $WRAP"

      - name: Strip deprecated MaxPermSize if present
        run: |
          WRAP="${{ steps.findgradle.outputs.wrap }}"
          PROJ_DIR=$(dirname "$WRAP")
          sed -i 's/-XX:MaxPermSize=[0-9]*m//g' "$PROJ_DIR/gradle.properties" 2>/dev/null || true
          mkdir -p ~/.gradle
          sed -i 's/-XX:MaxPermSize=[0-9]*m//g' ~/.gradle/gradle.properties 2>/dev/null || true

      - name: Build APKs (vector-app if present, else whole project)
        run: |
          set -e
          WRAP="${{ steps.findgradle.outputs.wrap }}"
          PROJ_DIR=$(dirname "$WRAP")
          chmod +x "$WRAP"
          cd "$PROJ_DIR"
          if ./gradlew --no-daemon :vector-app:projects >/dev/null 2>&1; then
            ./gradlew --no-daemon :vector-app:assembleDebug :vector-app:assembleRelease
          else
            ./gradlew --no-daemon assembleDebug assembleRelease
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: built-apks
          path: |
            **/build/outputs/apk/**/*.apk
